apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app-2
    spec:
      containers:
      - name: flask-app-2
        image: webapp:1
        # for local development against minikube registry
        #imagePullPolicy: Never        
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-2
  labels:
    app: flask-app-service-2
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 5001
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: flask-app-2
